### ISSUE TITLE
How to use user stories in the issue tracker

### ISSUE THREAD

**Issue by IshaaanVyas** [nus-cs2113-AY2122S1/forum#106]
My current understanding of user stories in the issue tracker is that they are just there for the record and not used as actual issues. eg. If something needs to be added then there would be an issue created called "Add something" and a separate user story for that issue (a new issue in the form of " As a user I need something" ) would be created, but mainly the "Add Something" issue would be used to assign to people and linked to pull requests.

But now I'm thinking I may have misunderstood and it might have been that the main "Add something" issue should have been renamed to be in a user story format (or the user story should have been in the description of the issue).

Would greatly appreciate anyone's advice on this, maybe its that both ways are valid but one way is better than the other?

**Comment by okkhoy** [comment]
To record the user stories please [see here](https://nus-cs2113-ay2122s1.github.io/website/admin/appendixE-gitHub.html#using-issues).

Instead of explaining the details of how to manage the issues, please take a look at the [repo I used in the lecture](https://github.com/okkhoy/Utilities/issues?q=is%3Aissue). I added a couple more example issues to help understand.

**Comment by IshaaanVyas** [comment]
Got it, thanks!
