### ISSUE TITLE
Array Length

### ISSUE THREAD

**Issue by jhsee5** [nus-cs2113-AY2122S1/forum#11]
![Arraylength](https://user-images.githubusercontent.com/70202843/130186237-2cc35b72-780f-40fb-9f2d-0583873a275b.png)

Hi there, I know this may seem trivial, I'd like to contest that scores.length is 5 instead of 4.

Anyone can attest to this please.

Thank you.

**Comment by richwill28** [comment]
Yes, <code>System.out.println(scores.length);</code> prints 4, because you initialized <code>scores</code> as an array of size 4. Java has 0-based indexing so an array of size 4 will start from index 0 to 3 (i.e. scores[0] until scores[3] is valid).

The line <code>scores[5] = 0;</code> throws the following error message during runtime (not compile-time).
<code>Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4</code>

**Comment by richwill28** [comment]
Btw, highly recommended that you write the code as markdown instead of image. This will make it easier for everyone to copy/paste the code and it supports syntax highlighting as well. For example,
```Java
int[] scores = new int[4];
System.out.println(scores.length);
scores[5] = 0;
```

Note: [Markdown guide](https://www.markdownguide.org/).

**Comment by SuibianP** [comment]
> Btw, highly recommended that you write the code as markdown instead of image. This will make it easier for everyone to copy/paste the code and it supports syntax highlighting as well. For example,
> 
> ```java
> int[] scores = new int[4];
> System.out.println(scores.length);
> scores[5] = 0;
> ```
> 
> Note: [Markdown guide](https://www.markdownguide.org/).

[Another source](https://meta.stackoverflow.com/questions/285551/why-not-upload-images-of-code-errors-when-asking-a-question) for this claim, with rationales.

**Comment by jhsee5** [comment]
Thank you @SuibianP  @richwill28 !
