### ISSUE TITLE
Convention in ordering methods in a class

### ISSUE THREAD

**Issue by naijie2108** [nus-cs2113-AY2122S1/forum#43]
Is there any convention when it comes to ordering methods in a class? For example, should I list all getters/setters first, then all public methods, followed by private utility methods? Or should I group public methods with the relevant utility methods instead (e.g extracted methods)?

**Comment by richwill28** [comment]
There seems to be two grouping methods adopted by most programmer, either grouping by functionality or scope/accessibility.

From what I can find..
* [Oracle](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html) seems to prefer grouping methods based on functionality rather than by scope/accessibility.
* [Robert C. Martin](https://stackoverflow.com/a/1760877) advises programmers to organize their member variables at the top of the class (constants first, then private members).
* Sun Microsystems' Java Coding Style Guide has very rigid organization. See [Section 6.1](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.443.7443&rep=rep1&type=pdf).

 Whichever one that you end up choosing, I think it is important to be consistent. Not sure if there is any specific requirement from this module though.

**Comment by okkhoy** [comment]
There is no specific module-specific requirement for this as mentioned by @richwill28 .
However, going by the general guideline ( for things not mentioned in the Java coding standards, follow Google style guide ) you can refer to [this](https://google.github.io/styleguide/javaguide.html#s3.4.2-ordering-class-contents).
You see that even in the Google style guide, there is no concrete rule as such. 
So maintain consistency in whatever you follow.

**Comment by naijie2108** [comment]
Thank you @richwill28  and prof @okkhoy
