### ISSUE TITLE
different ways of iterating through Java List (Coursemology Week 4, question3)

### ISSUE THREAD

**Issue by DuckWillow** [nus-cs2113-AY2122S1/forum#46]
![image](https://user-images.githubusercontent.com/71874189/131659694-53a5d5e0-8db5-4366-a357-be86649f0382.png)

When I was doing week4 coursemology, question3, I encounter this problem:
When I try to iterate the list 'shapes' using **for (Shape c: shapes)**, it gives me an error.
But when I change iteration to **for (int i=0;i<shapeCount;i++)**, it works.

May I ask why? Aren't they do the same job?

**Comment by zonglun99** [comment]
I think it is because of the initialisation of the array shape to size 100, when you run the first for loop, it gives an error because not all 100 spaces are used, whereas the second for loop you are iterating through the array with data (Circle and Rectangle) stored when you addShape instead of the whole array.

**Comment by DuckWillow** [comment]
> I think it is because of the initialisation of the array shape to size 100, when you run the first for loop, it gives an error because not all 100 spaces are used, whereas the second for loop you are iterating through the array with data (Circle and Rectangle) stored when you addShape instead of the whole array.

Thank you!
