### ISSUE TITLE
Accidentally merged local branch-Level-5 to local master branch with fast forward

### ISSUE THREAD

**Issue by xRossKoh** [nus-cs2113-AY2122S1/forum#54]
As the title suggests, I accidentally merged my local branch-Level-5 to my local master branch with fast forward. How will this affect the grading of my work? And is there anyway to revert the changes made with fast forward?

**Comment by nvbinh15** [comment]
If you have pushed every commits except the merge commit to the remote repo, simply clone the remote repo to you local machine, merge without fast-forward, and push it.

If not, since you have not pushed the commits to the remote repo, the fast-forward merge has not been detected by the grading script. You can refer to [this thread](https://stackoverflow.com/questions/2389361/undo-a-git-merge-that-hasnt-been-pushed-yet) to undo that merge. In case you have pushed your fast-forward merge to the remote repo, you can refer to [this](https://stackoverflow.com/questions/14308580/undo-a-fast-forward-merge) to restore the commits.

**Comment by okkhoy** [comment]
The way to fix is given above.
For tracking purpose, we need you to have the merge commit else you will be marked as "not completed" for that item.

**Comment by xRossKoh** [comment]
Thank you for your help. I realised that I had not pushed anything to master after creating the new branch and had been pushing to the remote branch-Level-5 while working on this week's increment. Hence, I used the "git reset --hard origin/master" command to reset my local master branch to be the same as the remote master branch, then merged with the local branch-Level-5 without fast forward.
