### ISSUE TITLE
Using list of datatypes

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#67]
Hi guys,

I'm quite curious, what is the difference between indicating and not indicating the data type in the latter "<>".

`private static List<Task> listOfTasks = new LinkedList<Task>();`

vs

`protected static List<Task> listOfTasks = new LinkedList<>();`

**Comment by nvbinh15** [comment]
Basically, they are the same. The second line uses a diamond operator `<>`, which is an example of type inference. Java can infer that `listOfTasks` should be an instance of `LinkedList<Task>` since the compile-time type of `listOfTasks` is `LinkedList<Task>`.

You can refer to the [CS2030S website](https://nus-cs2030s.github.io/2021-s2/24-inference.html) for more details.

**Comment by andrewtkh1** [comment]
Thank you!
